### ISSUE TITLE
Treat first build with watch as normal build

### ISSUE THREAD

**Issue by ansbar** [Amaimersion/remove-files-webpack-plugin#25]
Hi, thanks for a great plugin!
I know a simular request was made before and a (hacky) solution was presented =) so wanted to raise this again since I dislike hacky..

# Feature Request
I want the first startup build with webpack watch to trigger "before"-code.

## Summary
When starting a webpack watch session a "normal" build seems to be started followed by short "rebuilds" whenever a change is made. When using watch in this plugin it skips all "before"-code.

**Comment by Amaimersion** [comment]
Hello there!

I guess it is a (hacky) solution what you talking about - https://github.com/Amaimersion/remove-files-webpack-plugin/issues/22#issuecomment-591964140

**Comment by ansbar** [comment]
Yes, thats the one.

Would you agree that the startup build for watch should be considered a normal build (in before/after)?

**Comment by Amaimersion** [comment]
It really depends. 

Some developers want to apply `watch` rules even for first build in "watch" mode, some developers as it turned out want to apply `before` rules for first build in "watch" mode and `watch` rules for subsequent "watch "builds. So, it's all really depends on programmer logic.

As for `after` rules, these rules will be applied for both "normal" compilation and "watch" compilation. According to the 1.4.0 documentation:
>`after` – executes once after "normal" compilation and every time after "watch" compilation.

Anyway, you are right that webpack treats first build in "watch" mode as "normal" build, and next builds is just short rebuilds. Current `watch` behavior for "watch" mode: apply same rules for first build and subsequent rebuilds. 

You're not the first who asks for another behavior of `watch` for "watch" mode: apply `before` rules for first builds and `watch` rules for subsequent  rebuilds. According to "Insights > Traffic" people also google for it.

This is an obvious scenario, and i should have implemented this earlier. I will implement it in 1.4.1.

Thank you for request.

**Comment by Amaimersion** [comment]
Starting from 1.4.1 you can use such configuration:

```javascript
new RemovePlugin({
    // will be applied for every "normal" build and
    // for first build of "watch" build
    before: {
        // ...
    },
    // will be applied to each "watch" build, 
    // starting from the second one
    watch: {
        // ...
        beforeForFirstBuild: true
    }
})
```

**Comment by Amaimersion** [comment]
I'm closing this. Feel free to reopen if you have any questions/features/bugs relative to this issue.

**Comment by ansbar** [comment]
Hi @Amaimersion thanks for the update, working as expected!

You might want to add an example to the documentation, like:
```

// Remove distfolder all normal builds and first watch build.
new RemovePlugin({
            before: {
                include: [
                    './Content/dist'
                ]
            },
            watch: {
                beforeForFirstBuild: true
            }
        })
```

**Comment by Amaimersion** [comment]
I thought about adding some example with `beforeForFirstBuild` in readme. However, `beforeForFirstBuild` looks too simple and i think parameters description is enough to document this parameter. Current examples section contains only few simple cases for demonstration and some hard cases for additional documentation. If i will add many simple cases in examples section, then examples section will become "too much" and no one will read it. So, it is the reasons why i didn't add it.
